#!/usr/bin/env bash

# based on https://junegunn.github.io/fzf/tips/ripgrep-integration/
# with some changes:
#  - ignore svg & lock files
#  - sort with recently-modified at the bottom
#  - search in ~/workspace
#  - launch vscode on Enter and jump to file:line:column
#  - no header on bat

(RELOAD='reload:rg --sortr=modified --max-depth 4 --hidden --glob=!.git --hyperlink-format=vscode --max-filesize 500K --one-file-system --max-columns 150 --type-not svg --type-not lock --column --color=always --smart-case {q} || :'
 cd ~/workspace && fzf --disabled --ansi \
 --bind "start:$RELOAD" --bind "change:$RELOAD" \
 --delimiter : \
 --bind 'enter:execute(code --goto ~/workspace/{1}:{2}:{3} &)+execute(echo -n ~/workspace/)+accept' \
 --preview 'bat --style=numbers --color=always --highlight-line {2} {1}' \
 --preview-window '+{2}+4/3,<120(up)' \
 --query "$*" \
)
