#!/usr/bin/env bash


CHECKFILE=~/.config/chezmoi/dotfiles-status.check
MINUTES=10
if [ "$1" == "auto" ]; then
	if [ -e $CHECKFILE ]; then
		# file exists
		if find $CHECKFILE -type f -mmin +$MINUTES | grep --quiet .; then
			# file modified more than $MINUTES ago
			:
		else
			# file newer than $MINUTES
			# just quietly don't bother checking
			# "recently modified in last $MINUTES minutes, just exit"
			exit 1
		fi
		# "file is older than $MINUTES minutes"
	fi
fi

touch $CHECKFILE

RED='\033[0;31m'
NC='\033[0m' # No Color

function red() {
	echo -e "$RED$1$NC"
}

function replace_home() {
    python3 -c "import sys; from os.path import expanduser; home=expanduser('~'); [print(_.replace(home, '~'), end='') for _ in sys.stdin.readlines()]"
}

function indent() {
	awk '{print "\t"$0}'
}

chezmoi verify
if [ "$?" -ne 0 ]; then
	# not all target home directory files match the source repo
	red "Changes to managed dotfiles: (chezmoi status)"
	echo " -> chezmoi diff --reverse"
	echo " -> chezmoi re-add [file]"
	echo " -> chezmoi re-add --interactive"
	echo " -> chezmoi apply --interactive"
	chezmoi status --path-style absolute | replace_home | indent
	echo
fi

if [ "$(chezmoi unmanaged)" != "" ]; then
	red "Unmanaged dotfiles: (chezmoi unmanaged)"
	echo " -> chezmoi add"
	echo " -> $EDITOR .local/share/chezmoi/.chezmoiignore"
	chezmoi unmanaged --path-style absolute | replace_home | indent
fi
